/// SES API error object.
class SesSendError {
  final String code;
  final String message;

  const SesSendError({required this.code, required this.message});

  factory SesSendError.fromJson(Map<String, dynamic> json) {
    return SesSendError(
      code: json['Code']?.toString() ?? 'UnknownError',
      message: json['Message']?.toString() ?? 'Unknown error',
    );
  }

  @override
  String toString() => 'SesSendError($code: $message)';
}

/// SES send email response.
class SesSendResponse {
  /// Unique message ID generated by SES.
  final String messageId;

  /// Tencent Cloud request ID.
  final String requestId;

  /// Error object when request fails at API level.
  final SesSendError? error;

  const SesSendResponse({
    required this.messageId,
    required this.requestId,
    this.error,
  });

  /// 请求被接受：没有 API 错误，且 MessageId 去掉空白后仍非空。
  /// 缺字段、空串、只有空白都视为失败。
  bool get isOk => error == null && messageId.trim().isNotEmpty;

  factory SesSendResponse.fromJson(Map<String, dynamic> json) {
    final response = json['Response'] as Map<String, dynamic>? ?? {};
    final errorJson = response['Error'] as Map<String, dynamic>?;
    return SesSendResponse(
      messageId: response['MessageId']?.toString() ?? '',
      requestId: response['RequestId']?.toString() ?? '',
      error: errorJson == null ? null : SesSendError.fromJson(errorJson),
    );
  }

  @override
  String toString() =>
      'SesSendResponse(messageId: $messageId, requestId: $requestId, isOk: $isOk)';
}
